### ISSUE TITLE
Failed downloads

### ISSUE THREAD

**Issue by Druthulu** [TheNormalnij/7DTD-MVirus#3]
![image](https://github.com/user-attachments/assets/0124d994-28ed-46c2-a9bc-5e328c4c7695)

I edited the source to include Prefabs Dir for a test, and while a lot of them transfer, many fail.

If I re-join the server, it will attempt to download the missing ones, and it successes on a lot of them. 

But there is still a high failure rate. How can I gather a bit more data on these "error writing headers"?

Given, I am trying to transfer some 30,000 files

**Comment by TheNormalnij** [comment]
Does the server have something in logs too?

Prefabs support was added with the latest commit, btw.

**Comment by TheNormalnij** [comment]
I think, It was fixed with 85ec29c3be00a244909c5ed9a3528b26d88ff255.

**Comment by Druthulu** [comment]
No additional data in the server logs, nothing shows in the console on the server during file transfers.
Tested out the new commit, didn't see any failed downloads, but like only 5 out of the 50 mods downloaded. the client just sat at the "ready to spawn" button 
MVirus did the mod loads, but was missing tons of data.
Running commit 85ec29c on my port forwarded local server if you want to test against, the server is in EAST US, named "TEST MVIRUS" ports 26900-26905 are forwarded out.
206.221.176.183:26900
<property name="HttpPort" value="26905"/>

Ill leave the server up for a while in case you wanted to test. Im working on something else atm.

**Comment by Druthulu** [comment]
some extra info:
Server:
![image](https://github.com/user-attachments/assets/da2c8897-1f30-4260-a11d-e1cc66a635dc)

client:
![image](https://github.com/user-attachments/assets/2808d6d2-2b47-4177-a8bf-d8ac9e68fc3c)

**Comment by TheNormalnij** [comment]
Thanks you!
I'll check it today on your server at 16:00-22:00 GTM

**Comment by Druthulu** [comment]
sorry, my server may have went down, its back up again

**Comment by TheNormalnij** [comment]
ip was wrong too =)

**Comment by TheNormalnij** [comment]
I found some issues with your server.
* Race condition when the client is connecting to the server. Fixed
* Internal HTTP server handled requests synchronously. Now the http server is fully async.
* File paths can contain utf-8 characters and spaces. Serilaization was added.
* Added option to use external CDN and nginx/apache file servers.

**Comment by Druthulu** [comment]
new version worked great at first, shows download speed, but then disconnects after only downloading 100MB out of 11GB.
drops me to the main menu.
I see in the log failed sending request,
I reconnect, no download counter, and the server continues loading the world data/configs, etc. but I do see in the console also downloading the prefabs etc.
disconnect again,

Tried connecting again, no download, just ready to spawn button after loading configs.
![image](https://github.com/user-attachments/assets/30f16a23-b876-4c9b-a752-438678c83908)
cache is only 1.25Gb, server files same as last time.

Server rebooted and is up for you to test against again if you want.

Let me know if you want to create a version with logging or something to help you resolve these issues.

**Comment by TheNormalnij** [comment]
I downloaded 1.5gb from your server without any issues in single session. It took for me 2 hour, so I weren't waiting till the end. 

Is your internet connection with the server stable?
Does it work with disabled antivirus / firewall?
Can you attach your client logs, please.

If your AV blocks unprotected http requests, you can use nginx or apatche with let's encrypt ssl certificate as CDN.

**Comment by TheNormalnij** [comment]
> Tried connecting again, no download, just ready to spawn button after loading configs.

Are you sure that you updated the mod on the client as well?

**Comment by Druthulu** [comment]
yes I updated the client first, and the updated the server. both show the new config style with the external CDN config options. My AV isn't involved with regular http requests. I do have DNS over HTTPS setup at the router and browser level.

My server is hosted on a separate firewall zone and different subnet, but same external IP address. The server runs on a little intel NUC sitting on my router.
I have 1GB fiber up/down.
Port Forwarding is setup correctly to WAN and between the two zones. 
I use VisualSVN to checkout, edit, and upload very large files between the two zones, shouldn't be an issue there.

I was able to download 1.25GB from myself in the first attempt that only took a few minutes. That first connection did the progress text showing download amounts. Then failed to send request, and sent me back to the main menu, attempt to connect again, it continued to download, but no progress text, and it was loading configs during this like it did in previous versions. (this is the first version that showed me the download amount and paused loading configs until the download finished) then it sent me to the main menu again. When I reconnected again, no downloads were going, just loading configs, and allowed me to spawn in. 

The IP that 7 days lists is not my IP address, and I can't connect using direct IP to my true IP. I do have VPN split tunnels at the router level, but that only applies to traffic in a certain IP range, this is well outside of it. I assume its some sort of server browser redirect on TFP side of things.

The server console does show telnet requests from my local zones, but the server wont list in my lan tab within the game. all logs on the client side show the connection happening to the external IP listed in the server browser.

First download start time:
`2024-12-19T12:53:58 47.565 INF [MVirus] Download file: http://59.102.137.82:26905/Bdubs_Vehicles/Resources/a21vechs.unity3d`

`2024-12-19T12:55:52 161.242 INF [MVirus] Download file: http://59.102.137.82:26905/Fluffy_Panda_Mega_Mall/Prefabs/Parts/road_section_sc_09.tts
2024-12-19T12:55:52 161.266 ERR [MVirus] An error occurred while sending the request
2024-12-19T12:55:52 161.268 INF [MVirus] Downloading canceled
2024-12-19T12:55:52 161.269 WRN [MVirus] Server files are not downloaded. Disconnect`

This was the first disconnect, after downloading a lot of files.

So I downloaded over 1GB within just a few minutes. no failures like before during this time. 
Client log
[output_log_client__2024-12-19__12-53-09.txt](https://github.com/user-attachments/files/18213981/output_log_client__2024-12-19__12-53-09.txt)

After the second disconnect, when I connected for the third time, no MVIRUS activity happened.

Another note:
![image](https://github.com/user-attachments/assets/a9f0eb0c-f759-4f13-8e62-1fbb69c60228)
This is what client side mods look like. These all have a DLL, and some have both a DLL and a unity3d file. I saw in the logs it failing to load one of these because it was expecting to have downloaded it from you. Not sure if that is causing a problem.
[client-Mods.zip](https://github.com/user-attachments/files/18214033/client-Mods.zip)

Startup Optimizer also does some funky stuff with repacking unity3d files using a different compression method, again, not sure if that is causing problems. just extra info.

**Comment by TheNormalnij** [comment]
> I have 1GB fiber up/down.

The code creates a new connection for every download. Potentially, your PC creates a lot of active connections.
The client shares one connection between downloads now. It didn't work before for unknown reasons.

> After the second disconnect, when I connected for the third time, no MVIRUS activity happened.

It's fixed now

Thanks you for details and the server!

**Comment by Druthulu** [comment]
commit e8824c9

2024-12-21T19:32:38 46.426 INF [MVirus] Request server mods
2024-12-21T20:01:27 1775.252 INF [MVirus] All download tasks complected

No failures. about 30 minutes download time, 11GB of mods
all mods loaded, join and can see prefabs, unity3d blocks, and item icons.

2nd join
2024-12-21T20:14:48 39.988 INF [MVirus] Request server mods
2024-12-21T20:16:09 121.408 INF [MVirus] All download tasks complected


Test 2 - deleted client cache
2024-12-21T20:27:14 32.068 INF [MVirus] Request server mods
2024-12-21T20:55:46 1744.153 INF [MVirus] All download tasks complected

2nd join
2024-12-21T21:33:21 125.673 INF [MVirus] Request server mods
2024-12-21T21:34:43 207.715 INF [MVirus] All download tasks complected

everything is great now, thank you!

> Thanks you for details and the server!

I'm a test engineer, always fun to help others with their projects.
