### ISSUE TITLE
Multiple server support

### ISSUE THREAD

**Issue by Druthulu** [TheNormalnij/7DTD-MVirus#7]
Create subfolders within the cache folder for different servers.

**Comment by TheNormalnij** [comment]
> Create subfolders within the cache folder for different servers.

What problem does this solve?

**Comment by Druthulu** [comment]
Joining two different servers with different mod sets, I haven't tried it yet, but how would MVirus handle the cache? would it add to the cache and only activate the mods required for the single server you are joining? Would it delete the cache when connecting to a different server?

**Comment by TheNormalnij** [comment]
> would it add to the cache and only activate the mods required for the single server you are joining

This is current behavior.
